### ISSUE TITLE
Trendline showing wrong direction

### ISSUE THREAD

**Issue by evalerr** [Makanz/chartjs-plugin-trendline#1]
Trendline showing wrong direction when the array contains NULLS or ZEROS.

Could there be an option to use regression.    

Would be good if the readme file mentions how the trendline is calculated.

Thanks,  looks very promising.   have a great festive season

**Comment by Makanz** [comment]
Thanks for your feedback. I will look into it.

**Comment by Makanz** [comment]
Please try the new version v0.2.1.
