### ISSUE TITLE
Getting trendline dataset

### ISSUE THREAD

**Issue by elorenzorodz** [Makanz/chartjs-plugin-trendline#100]
Is there anyway to get the dataset for the trendline? Including X,Y of the data within the dataset.

**Comment by Makanz** [comment]
Can you give me a example config to try with?

**Comment by elorenzorodz** [comment]
Here is my dataset, chart config I did was just default.

```
datasets: [
    {
        label: '',
        pointRadius: 0,
        pointHoverRadius: 4,
        borderColor: '3',
        borderColor: '#FF7A48',
        data: [0, 0, 0, -72.47, 362.37, 0, 0, 37.27, 450, -2000, -2000, -2000],
        tension: 0.5,
        pointHoverBackgroundColor: '#FF7A48',
        fill: false,
        trendlineLinear: {
            colorMin: "#D1D1D1",
            colorMax: "#D1D1D1",
            lineStyle: "dashed",
            width: 3,
            projection: true,
        },
    }
]
```

I also created a custom plugin for `afterDatasetsDraw` to try to read the dataset of the trendline created, but couldn't find it.

```
const customLabelPlugin = {
    id: 'customLabelPlugin',
    afterDatasetsDraw: function (chart) {
         // omitted
        }
    }
};

Chart.register(customLabelPlugin);
```

I just need to get the x,y coordinates of the last data in the dataset.

**Comment by Makanz** [comment]
The trendline is drawn directly in the canvas and is not saved. You can see that in the code.
Please describe more specifically what you want to achieve and maybe I can help.

https://github.com/Makanz/chartjs-plugin-trendline/blob/main/src/chartjs-plugin-trendline.js#L206
