### ISSUE TITLE
 trendlineLinear with react-chartjs-2

### ISSUE THREAD

**Issue by artworkjpm** [Makanz/chartjs-plugin-trendline#17]
I installed the pluggin and added to my dataset, but the line doesn't seem to show. Other issues here seemed to have had it fixed, any ideas?

` datasets: [
        {
          label: "New York",
          data: NY.map(item => {
            return { x: item.year, y: item.max.toFixed(2) };
          }),
          trendlineLinear: {
            style: "red",
            lineStyle: "line",
            width: 1
          },
          pointBackgroundColor: "black",
          borderColor: "black",
          backgroundColor: "black",
          borderWidth: 1,
          showLine: false,
          fill: false,
          pointStyle: "cross"
        }
}
]`

Maybe its because I'm not importing into react? How do I do that because its a pluggin of chart.js. Doing `import {trendlineLinear} from "chartjs-plugin-trendline"` hasn't worked

**Comment by artworkjpm** [comment]
actually I solved this by copying code from a d3.js trendline solution I found, I copied the code the make a starting and end point, then create a new Line data set https://gist.github.com/isaaguilar/fb92517c1ce878f7d3780cf9aa74a709

**Comment by w4** [comment]
This plugin expects `Chart` to be in the global scope to register itself so it's easy enough to add a little method to `window` to forward registers on to the `Chart` instance `react-chartjs-2` has in its scope without exposing the whole thing.

```
import { Chart } from "react-chartjs-2";

window.Chart = { plugins: { register: (...x) => Chart.plugins.register(...x) }};
require('chartjs-plugin-trendline');
delete window.Chart;
```

**Comment by Makanz** [comment]
Please try the new version v0.2.1. Maybe it will solve your problem.
