### ISSUE TITLE
Trendlines for react-chartjs?

### ISSUE THREAD

**Issue by clydehunt76** [Makanz/chartjs-plugin-trendline#2]
I am actually using the react-chartjs-2 module which wraps chartjs v2.5+. Trendline isnt working for me but Im just looking to confirm if it simply wont, or if it should then its something Im coding. I have simply added the trendlineLiner config to the options object of a bar chart but no trendline is appearing

**Comment by clydehunt76** [comment]
User error, sorry

**Comment by travisanderson** [comment]
What ended up being the issue?

**Comment by artworkjpm** [comment]
I'm using react-chartjs-2 and need to put a trend line in, adding :

` trendlineLinear: {
            style: "#3e95cd",
            lineStyle: "line",
            width: 1
          }`

Doesn't add a trendline, I'm not sure how to import the module as well as its plugging being called in the dataset.
