### ISSUE TITLE
Trendline start at first datapoint possible?

### ISSUE THREAD

**Issue by Rudolfiii** [Makanz/chartjs-plugin-trendline#20]
Currently im using the chartjs-plugin-trendline on a linechart with the X and Y format in angular 7. I got the trendline working and it works quite good! There is one issue though:

In my case the trendline is only useful when the trendline starts at the first datapoint of my dataset.

Is it possible to do make the trendline start at the first datapoint of my dataset?

**Comment by Makanz** [comment]
Sorry for a very late reply. Please show me a screenshot of your chart.
