### ISSUE TITLE
Line jumps when toggling dataset

### ISSUE THREAD

**Issue by Elschnuppero** [Makanz/chartjs-plugin-trendline#24]
First of all thank you for the amazing plugin :)

But i have an issue: i have a graph with multiple datasets and only the first dataset uses the trendline. All others are hidden at the beginning and all works fine.

![Screenshot_2019-12-31 Visual Charts](https://user-images.githubusercontent.com/20712214/71619782-55218300-2bc6-11ea-889d-25241600f7cb.png)

But when i toogle the first dataset and show another one the line jumps. I attached a screen since its hard to explain.

![Screenshot_2019-12-31 Visual Charts(1)](https://user-images.githubusercontent.com/20712214/71619802-7aae8c80-2bc6-11ea-81f0-baa964ede37b.png)

Thank you

**Comment by Makanz** [comment]
Sorry for my late reply. Please send me some example code to test with.
