### ISSUE TITLE
Trendline outside of chart area boundary

### ISSUE THREAD

**Issue by bfalchuk** [Makanz/chartjs-plugin-trendline#26]
I'm using latest trendline with scatter chart and also using the chartjs-zoom-pan plugin.  While trendline seems to be computed correctly i get anomalous behavior when i drag the chart. The trendline wants to use the white area to the left and right of the chart for drawing itself, but this is not a charting area (scatter dots do not show same behavior). 
![Capture](https://user-images.githubusercontent.com/26441959/73566466-ec7e2e00-4431-11ea-82f6-0c2130159bab.PNG)

**Comment by TheRatG** [comment]
Hello, thanks for plugin. Have the same problem

![Screenshot 2020-11-26 at 11 45 29](https://user-images.githubusercontent.com/1580318/100334838-f5ea0f80-2fdc-11eb-9f13-b441dc4aa692.png)

**Comment by Makanz** [comment]
@TheRatG Is it possible for you to send me some example code that I could investigate?

**Comment by TheRatG** [comment]
@Makanz sorry for inconvenience, I used to use old version 0.1.0. Latest version works fine.
