### ISSUE TITLE
Trendline works fine only if all y values are defined?

### ISSUE THREAD

**Issue by marcellocarrabba** [Makanz/chartjs-plugin-trendline#34]
I attach two screenshots. 
Is there a work around to the problem?
First case, all data is defined: works
![download](https://user-images.githubusercontent.com/54410351/81601542-4d22ec80-93cb-11ea-9028-c187a623a04a.png)

Second case, one y value is zero.
![download (1)](https://user-images.githubusercontent.com/54410351/81601566-5c099f00-93cb-11ea-93cc-e6b5f55b8d86.png)

**Comment by marcellocarrabba** [comment]
To be exact: the value at day 24 is not zero but undefined

**Comment by Makanz** [comment]
Please try the new version v0.2.1. Maybe it will solve your problem.

**Comment by Makanz** [comment]
Please try the latest version v1.0.2

**Comment by btangsp** [comment]
Hi, I'm currently using v2.0.2 but when any of the values in an array are either null or undefined, it crashes completely.

When using v1.0.3 it no longer crashes, but like the others above me, the trendline doesn't show up at all.

**Comment by Makanz** [comment]
Please provide me a example when it is not working. I tried with a barchart with the following data and that works.

```                            
                          data: {
                                labels: ["Africa", "Asia", "Europe", "Latin America", "Undefined", "null", "North America"],
                                datasets: [
                                    {
                                        label: "Population (millions)",
                                        backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
                                        data: [2478,5267,734,784,undefined, null,433],
                                        trendlineLinear: {
                                            colorMin: "rgba(255,105,180, .8)",
                                            lineStyle: "dotted",
                                            width: 2
                                        }
                                    },
                                ]
                            },`

**Comment by Makanz** [comment]
@btangsp I have released a new version today. Please try it out and see if it solves your problem.
