### ISSUE TITLE
Trendline projecting out future values

### ISSUE THREAD

**Issue by dkmarsh99** [Makanz/chartjs-plugin-trendline#37]
Hi. I have a graph that has values for Jan, Feb, Mar and April. I have added the trendline and that works ok. What my customer wants is the trendline to project out for the remaining months of the year based on a linear regression for the values that were there and projecting out the future values. Is this possible. Also want to add a legend entry for the trend line - is this possible ? Thanks.

**Comment by Makanz** [comment]
I'm not planning to implement that. If you solve it feel free to submit a pull request.

**Comment by shkuviak** [comment]
I've implemented this feature with #44, you can check

**Comment by Makanz** [comment]
Thanks for you remainder and the PR. I will look at it soon.
