### ISSUE TITLE
Other trendlines functions

### ISSUE THREAD

**Issue by bagit** [Makanz/chartjs-plugin-trendline#46]
Hello,

first of all I'm so glad to use your trendline plugin, I'd been looking for such a plugin for a long time.

It works fine! Thank you!

I wonder if you would plan other trendlines functions than linear: polynomial, exponential...?

And if one day we could change the trendline type just like this:

(exponential for example)

`trendlineExponential: {
          style: "rgb(0, 0, 0, 0.7)",
          lineStyle: "solid",
          width: 1
                        }`

Is this something you may think about?

Best wishes for this new year.

**Comment by Makanz** [comment]
I dont have any plans to add other types of trendlines for now. Feel free to submit a pull request if you have the possibility to contribute.
