### ISSUE TITLE
How to define specific data to be calculated in trendline

### ISSUE THREAD

**Issue by bagaskarala** [Makanz/chartjs-plugin-trendline#47]
![image](https://user-images.githubusercontent.com/14112952/106705787-32f80100-6621-11eb-9d83-d9620d092fef.png)

## Case
I only want use data from 00 until 12 to create trendline, so the trendline will not include the latest data. How to implement this case?

Note: i want only data inside blue border which is calculated to form trendline

**Comment by Makanz** [comment]
Please send me some example data that I can take a look at.
