### ISSUE TITLE
Trendline does not show

### ISSUE THREAD

**Issue by HetalRupareliya91** [Makanz/chartjs-plugin-trendline#5]
i have added chartjs-plugin-trendline.js file but it does not show the trend line Please help me

Here is my code

Html Code 

<canvas id="base" class="chart-bar" chart-labels="vm.ts_labels" class="chart chart-line" chart-data="vm.generalSatisfactionLine" chart-dataset-override="vm.overallGraphDataOveride" chart-options="vm.overallGraphOptions"></canvas>

angular js code

        vm.overallGraphOptions = {
            elements:
                {
                    point:
                        {
                            radius: 9,
                            hoverRadius: 7.5
                        }
                },

            trendlineLinear: {
                style: "rgba(255,105,180, .8)",
                width: 2
            }
            layout: {
                padding: {
                    left: 5000,
                    right: 0,
                    top: 0,
                    bottom: 0
                }
            },

            scales: {
                xAxes: [{
                    gridLines: {
                        display: true
                    },
                    ticks: {
                        display: true
                    }
                }],
                yAxes: [{
                    type: "linear",
                    position: "left",
                    id: 'satisfaction',
                    gridLines: {
                        display: true
                    },
                    ticks: {
                        display: true,
                        min: 0,
                        max: 10,
                        callback: function (label, index, labels) {
                            return label * 10;
                        },
                    },
                    labels: {
                        show: true,
                    }
                },
                {
                    type: "linear",
                    position: "right",
                    id: 'responses',
                    gridLines: {
                        display: false
                    },
                    ticks: {
                        display: false
                    },
                    labels: {
                        show: true,
                    }
                }],
            }
        }

**Comment by Gimmeaphatbeat** [comment]
+1

**Comment by Makanz** [comment]
Sorry for my late reply.

I hope this example code will help you. 
```javascript   
 new Chart(document.getElementById("bar-chart"), {
        type: 'bar',
        data: {
            labels: ["Label 1", "Label 2", "Label 3", "Label 4", "Label 5"],
            datasets: [
                {
                    label: "Population",
                    backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
                    data: [2478,5267,734,784,433],
                    trendlineLinear: {
                        style: "rgba(255,105,180, .8)",
                        lineStyle: "dotted",
                        width: 2
                    }
                }
            ]
        },
        options: {
            legend: { display: false },
            title: {
            display: true,
            text: 'Chart header'
            }
        }
    });
```

**Comment by lahiruhashan** [comment]
Does this work for in angular 6 as well?

**Comment by chrislawes79** [comment]
Does this work in scatter charts?

**Comment by lahiruhashan** [comment]
> Does this work in scatter charts?

yes. Check this chart : [](https://www.chartjs.org/samples/latest/charts/scatter/basic.html)

**Comment by mazoqui** [comment]
I've also noticed that it does not work while defining more than one y scale (as in the reported description)
By sharing a single Y scale among lines, the plugin does not raise any exception.
