### ISSUE TITLE
Trendline overlaps the y-axis label if there are data points outside of the range of the x-axis

### ISSUE THREAD

**Issue by vibonacci** [Makanz/chartjs-plugin-trendline#52]
![image](https://user-images.githubusercontent.com/9674553/115415670-647f7200-a1f7-11eb-9ccd-414cbcdda1de.png)

Picture speaks for itself. I use chartjs in combination with chartjs-plugin-zoom. Any solution for this?

**Comment by Makanz** [comment]
I dont know a solution right know but I will look at it when I have time.

**Comment by kwiats** [comment]
@vibonacci did you find solution?
