### ISSUE TITLE
Adding gradient information for the trendline

### ISSUE THREAD

**Issue by volokh1** [Makanz/chartjs-plugin-trendline#58]
I have added the trendline, but the most interesting information for me is its slope/gradient. Could it possible to make this information available so I can not only draw the trendline but also display the value of its gradient?

Thanks a lot!

**Comment by Makanz** [comment]
I don´t have any plans to add this information but feel free to contribute with a PR if you have the possibility.

**Comment by igor90** [comment]
Hey
Thank you for good package
I added simple gradient line for chart
Please check the PR
https://github.com/Makanz/chartjs-plugin-trendline/pull/67

**Comment by shkuviak** [comment]
I think that you can access it via the `scale` property:
https://github.com/Makanz/chartjs-plugin-trendline/blob/6601aae9a7d4c7b0129699a4d48cacbc23d66f93/src/chartjs-plugin-trendline.js#L200-L205
