### ISSUE TITLE
TrendLine overlaps Tooltip + Solution. Issue = afterDraw() 

### ISSUE THREAD

**Issue by Udemology** [Makanz/chartjs-plugin-trendline#61]
I notice that the trendlines overlap the Tooltips. 

I am not familiar with github pull requests and option but I thought maybe by showing the code here that any of the contributors could pick it up. As I love this nice plugin. 

The Issue: 
Looking at the code I saw the afterDraw() being used. That is creating the trendline after everything else in the canvas has been draw. This is called drawing time in canvas. Tooltips are set on afterDraw() as they will be on top. So this plugin which would load after everything else that has been draw will do exactly the same on top of the tooltip. 

Solution: 
Instead of afterDraw the drawing time should be after the datasets (the bar shapes or line elements) has been draw. To do this the code of **afterDraw()** must be replaced with **afterDatasetsDraw()**. 

// in this line is your issue: 
`var pluginTrendlineLinear={id:"chartjs-plugin-trendline",afterDraw:function(t){var i,e;for(var a in t.scales)if("x"==a[0]?`

// It should be:
`var pluginTrendlineLinear={id:"chartjs-plugin-trendline",afterDatasetsDraw:function(t){var i,e;for(var a in t.scales)if("x"==a[0]?
`

I already solved it in my own code but hope anyone can solve it so everyone else will benefit it.

**Comment by Makanz** [comment]
Thanks. I will implement this change.
