### ISSUE TITLE
Simple Gradient Line

### ISSUE THREAD

**Issue by igor90** [Makanz/chartjs-plugin-trendline#68]
Hey
First of all thank you for a great package

I added simple gradient trend line here
Could you check
https://github.com/Makanz/chartjs-plugin-trendline/pull/67

**Comment by igor90** [comment]
Hey
I also added the fill possiblity
Please check and let me know what should i add there for merging

Also I will update the type definitions

**Comment by Makanz** [comment]
Thanks! This is merged and a new version is out.
