### ISSUE TITLE
New error: Failed to execute 'createLinearGradient'

### ISSUE THREAD

**Issue by directos** [Makanz/chartjs-plugin-trendline#69]
When use `data: [0]` in order to inicialize the chart ...
New issue in all charts with trendlineLinear: Uncaught TypeError: Failed to execute 'createLinearGradient' on 'CanvasRenderingContext2D': The provided double value is non-finite. (at addFitter, chartjs-plugin-trendline.js:132:23)

Using:
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.8.0/dist/chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-trendline"></script>
Chart:
 . . .
trendlineLinear: {
colorMin: "red",
colorMax: "green",
lineStyle: "dotted",
width: 1,
projection: false
 }
 . . .

**Comment by directos** [comment]
Solved using `data: []`
Thanks!

**Comment by nileshdev0707** [comment]
but it will remove line too
