### ISSUE TITLE
Is data structure only support number array?

### ISSUE THREAD

**Issue by GRXself** [Makanz/chartjs-plugin-trendline#71]
In [chartjs official doc](https://www.chartjs.org/docs/latest/general/data-structures.html), it supports pure number array
```
const cfg = {
  type: 'bar',
  data: {
    datasets: [{
      data: [20, 10],
    }],
    labels: ['a', 'b']
  }
}
```
and object array
```
const cfg = {
  type: 'line',
  data: {
    datasets: [{
      data: [{x: 10, y: 20}, {x: 15, y: 30}, {x: 20, y: 10}]
    }]
  }
}
```
But when I try to use the object array with trendline plugin, the trendline didn't show up. I have debuged it and find that the createLinearGradient was using an extreme large x1 and x2 value(when the data is as above, the x1 is 536.3... , x2 is 1045.2... , while y1 is 60.15, and y2 is 116.4... Not sure if that make the trendline disappeared.
And if the x value in data is string,
```
const cfg = {
  type: 'line',
  data: {
    datasets: [{
      data: [{x: '2016-12-25', y: 20}, {x: '2016-12-26', y: 10}]
    }]
  }
}
```
the x1, x2 will both be 32767, that's the integer's border. While y1 and y2 will be NaN

**Comment by Makanz** [comment]
I have released a new version today that should address this problem. Version 2.0.3.
