### ISSUE TITLE
Not working with chart.js Version 4.x

### ISSUE THREAD

**Issue by tomherold** [Makanz/chartjs-plugin-trendline#72]
Do you have any suggestions on how to make this working in chat.js versions 4.x?

**Comment by tomherold** [comment]
Has been resolved.

**Comment by Makanz** [comment]
What was the solution?

**Comment by tomherold** [comment]
I accidently had an older version of chart.js

**Comment by Makanz** [comment]
Thanks for your answer. I will close the issue.
