### ISSUE TITLE
Bug: Trendline is broken when data is an object

### ISSUE THREAD

**Issue by mariadb-ThienLy** [Makanz/chartjs-plugin-trendline#74]
When `data` is an array of number, it works fine.
```js
let chartData = {
    labels: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
    ],
    datasets: [
        {
            label: 'Data One',
            backgroundColor: '#f87979',
            data: [40, 20, 12, 39, 10, 40, 39, 80, 40, 20, 12, 11],
            trendlineLinear: {
                colorMin: '#2d9cdb',
                colorMax: '#2d9cdb',
                lineStyle: 'solid',
                width: 2,
            },
        },
    ],
}
```
But it's not when data is an object:
```js
let chartData = {
    datasets: [
        {
            label: 'Data One',
            backgroundColor: '#f87979',
            data: [
                { y: 40, x: 'January' },
                { y: 20, x: 'February' },
                { y: 12, x: 'March' },
                { y: 39, x: 'April' },
                { y: 10, x: 'May' },
                { y: 40, x: 'June' },
                { y: 39, x: 'July' },
                { y: 80, x: 'August' },
                { y: 40, x: 'September' },
                { y: 20, x: 'October' },
                { y: 12, x: 'November' },
                { y: 11, x: 'December' },
            ],
            trendlineLinear: {
                colorMin: '#2d9cdb',
                colorMax: '#2d9cdb',
                lineStyle: 'solid',
                width: 2,
            },
        },
    ],
}
```
It could be a bug in the library as it shows this error
`Failed to execute 'createLinearGradient' on 'CanvasRenderingContext2D': The provided double value is non-finite.`

Here is a reproducible sandbox when data is an array of objects:
https://codesandbox.io/s/data-as-object-i4tjdb?file=/src/index.js

When data is an array of numbers: https://codesandbox.io/s/working-trendline-q31h0o?file=/src/index.js

My assumption is that this library doesn't support data objects. So data objects using custom properties would not work as well.
https://www.chartjs.org/docs/3.9.1/general/data-structures.html#object-using-custom-properties

**Comment by Makanz** [comment]
Thanks for the great info about it. I'll try to look into it.

**Comment by nileshdev0707** [comment]
any update on this , i am also getting this issue

**Comment by nileshdev0707** [comment]
I found a solution for this it was issued. labels and data  if any of this is empty it will give this error
if make sure  it has some values and is not empty array

**Comment by Makanz** [comment]
I have released a new version today that should address this problem. Version 2.0.3.
