### ISSUE TITLE
trendline does not support time scale?

### ISSUE THREAD

**Issue by reinertisa** [Makanz/chartjs-plugin-trendline#80]
Hi @Makanz I use **chartjs** library. I use trend line for linear scale. I do not see trendline for time scale and I got an this error. `'createLinearGradient' on 'CanvasRenderingContext2D': The provided double value is non-finite.` 

```
scales: {
   x: {
         type: 'time'
         time: {
              unit: 'day'
         }
      }
  }
```
I use the same data for linear scale and time scale. 
```
data = {
    "labels": [
        "2023-01-01T08:00:00.000Z",
        "2023-01-02T08:00:00.000Z",
        "2023-01-03T08:00:00.000Z",
        "2023-01-04T08:00:00.000Z",
    ],
    "datasets": [
        {
            "label": "Default",
            "data": [65,59,80,81],
            "trendlineLinear": {
                "colorMin": "red",
                "colorMax": "green",
                "lineStyle": "dotted",
                "width": 2,
                "projection": false
            }
        }
    ]
}
```

**Comment by Makanz** [comment]
I think it's the same problem as the issue #79 that I'm working on. Thanks for the information and example.

**Comment by reinertisa** [comment]
I am kind of busy at work but I hope this weekend I will create it. Thanks.

**Comment by Bliksempie** [comment]
Hi,

I have a similar issue where I do not get any error, yet, the trend line does not appear. Here is my `data` variable - the graph displays perfectly otherwise, but no trendline.

`
{
  "labels": [
    "2023-08-10 20:00:00",
    "2023-08-10 21:30:00",
    "2023-08-10 22:30:30",
    "2023-08-11 07:00:00",
    "2023-08-11 07:15:00",
    "2023-08-11 08:00:00"
  ],
  "datasets": [
    {
      "type": "line",
      "label": "Blood Sugar",
      "data": {
        "2023-08-10 21:30:00": "6.20",
        "2023-08-10 22:30:30": "6.60",
        "2023-08-11 07:00:00": "5.90",
        "2023-08-11 08:00:00": "4.60",
        "2023-08-11 11:17:00": "5.10",
        "2023-08-11 12:15:00": "4.90"
      },
      "backgroundColor": "#A9CCE3",
      "pointStyle": "circle",
      "pointRadius": 6,
      "pointHoverRadius": 12,
      "borderColor": "#5DADE2",
      "trendlineLinear": {
        "colorMin": "red",
        "colorMax": "green",
        "lineStyle": "dotted",
        "width": 3,
        "projection": true
      }
    }
  ]
}
`

Please can you advise? I think it has to be with the dates in the X-axis labels, if I understand the issue correctly.

**Comment by Makanz** [comment]
> Hi,
> 
> I have a similar issue where I do not get any error, yet, the trend line does not appear. Here is my `data` variable - the graph displays perfectly otherwise, but no trendline.
> 
> ```
> {
>   "labels": [
>     "2023-08-10 20:00:00",
>     "2023-08-10 21:30:00",
>     "2023-08-10 22:30:30",
>     "2023-08-11 07:00:00",
>     "2023-08-11 07:15:00",
>     "2023-08-11 08:00:00"
>   ],
>   "datasets": [
>     {
>       "type": "line",
>       "label": "Blood Sugar",
>       "data": {
>         "2023-08-10 21:30:00": "6.20",
>         "2023-08-10 22:30:30": "6.60",
>         "2023-08-11 07:00:00": "5.90",
>         "2023-08-11 08:00:00": "4.60",
>         "2023-08-11 11:17:00": "5.10",
>         "2023-08-11 12:15:00": "4.90"
>       },
>       "backgroundColor": "#A9CCE3",
>       "pointStyle": "circle",
>       "pointRadius": 6,
>       "pointHoverRadius": 12,
>       "borderColor": "#5DADE2",
>       "trendlineLinear": {
>         "colorMin": "red",
>         "colorMax": "green",
>         "lineStyle": "dotted",
>         "width": 3,
>         "projection": true
>       }
>     }
>   ]
> }
> ```
> 
> I have edited the data (as it contains sensitive information) and I have removed other parts of the graph that has no bearing to what I want to achieve. The full graph looks something like this (made smaller to crop sensitive info).
> 
> ![image](https://user-images.githubusercontent.com/677410/263546291-32ed0c17-9202-4e7e-b236-4289afd7ca50.png)
> 
> Please can you advise? I think it has to be with the dates in the X-axis labels, if I understand the issue correctly.

I tried with a array instead and then I worked. I can take a look at the later if it´s not working with array.
Example
 "data": [
            "6.20",
            "6.60",
            "5.90",
            "4.60",
            "5.10",
            "4.90"
        ],

![image](https://github.com/Makanz/chartjs-plugin-trendline/assets/4232943/163ec30b-900b-42e6-a444-b01d9c4bda72)

**Comment by Bliksempie** [comment]
Hi, thanks for the response - with an array with numerical indexes, it works, but because the data is tied to time, it is now distorted. There is not an even time between events I measure, so with a numerical array, I am losing the time range.

I will appreciate your feedback once you have any. Thanks!

**Comment by reinertisa** [comment]
@Makanz I created issue on  https://codepen.io/Isa-Reinert/pen/poqgEEX

**Comment by Makanz** [comment]
@reinertisa I have made a fix and created a PR. Do you have time to try it out before I make a merge?

**Comment by reinertisa** [comment]
@Makanz I tested PR and works pretty well. Thanks.
