### ISSUE TITLE
can't load directly in browser version 2.2.1 with chartjs 4.4.3

### ISSUE THREAD

**Issue by jgrayson-apl** [Makanz/chartjs-plugin-trendline#89]
Trying to use 2.1.1 (and chartjs 4.4.3) via "Load directly in the browser" method and receiving the following browser error:

_Uncaught SyntaxError: Cannot use import statement outside a module (at chartjs-plugin-trendline.min.js:17:1)_

Is there live example such as a CodePen or similar that we can check out?

**Comment by Makanz** [comment]
Sounds like I have introduced a bug in the latest version. Thanks for letting me know. I will try to solve it asap.

**Comment by jgrayson-apl** [comment]
Thanks for checking as I'd love to use what's already been done instead of trying to do this myself.

**Comment by Makanz** [comment]
Are you using the cdn/jsdelivr ?
Then try with 
https://cdn.jsdelivr.net/npm/chartjs-plugin-trendline/dist/chartjs-plugin-trendline.min.js

**Comment by jgrayson-apl** [comment]
Thank you, using that url no longer throws the error so now I can try and figure out the how to use it...
