### ISSUE TITLE
Trendline is drawn behind the bar chart

### ISSUE THREAD

**Issue by krishdev** [Makanz/chartjs-plugin-trendline#9]
![image](https://user-images.githubusercontent.com/11788554/51965526-6f3f6800-242f-11e9-987e-9abdfe5c666c.png)
Thanks for this amazing line. I have a difficulty in continuing with this fix.

As you can see in the image that the trend line is being drawn behind the chart. Is there a way to bring the trend line to front.

Appreciate your help.

**Comment by apoorvmote** [comment]
Yes I am also having same issue. Trend line is drawn behind bar chart. How do I draw it in front?

**Comment by txflow** [comment]
I think you can fix this in the chartjs-plugin-trendline.js file by changing 'beforeDraw' at the beginning to 'afterDraw'. This draws the trendline after the chart has already been drawn instead of before, so the trendline will be on top.

**Comment by apoorvmote** [comment]
@txflow I did exactly what you said and it worked for me. Thank you very much.

**Comment by dhwang** [comment]
> I think you can fix this in the chartjs-plugin-trendline.js file by changing 'beforeDraw' at the beginning to 'afterDraw'. This draws the trendline after the chart has already been drawn instead of before, so the trendline will be on top.

Should make a PR with this fix.

**Comment by Makanz** [comment]
Please try the new version v0.2.1.
