### ISSUE TITLE
Issue with Vite and Docker

### ISSUE THREAD

**Issue by IlyaLisov** [Makanz/chartjs-plugin-trendline#91]
I use Vite for building production code. 
I used this import for trendline to code be compiled:
```
import * as trendlinePlugin from "chartjs-plugin-trendline";

Chart.register(
	...,
	trendlinePlugin
);
```
After opening components with chart, I get exceptions like this:
![telegram-cloud-photo-size-2-5244859263120175125-x](https://github.com/user-attachments/assets/0515b1fe-bb8b-4662-957b-9bc8c8f9bd0f)

After removing trendline from registration problem dissappeared.
In local deployment everything works

Versions:
```
"chart.js": "^4.2.1",
"chartjs-plugin-trendline": "^2.1.1",
```

**Comment by Makanz** [comment]
Make sure you are using the latest version 2.1.2. there is a bug in 2.1.1.

**Comment by IlyaLisov** [comment]
I still have same exception

**Comment by IlyaLisov** [comment]
I think problem is in my import. Because I imported `*`, Chart.js can do something in registration and get an error. So Without import `*` I can't build project with Vite. I think I need to change something in my config
